version: '3.8'

services:
  mysql_prod:
    image: mysql:8.0
    container_name: mysql_binlog_production
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .mysql_production/data:/var/lib/mysql
      - ./scripts_mysql:/docker-entrypoint-initdb.d
    ports:
      - "5001:3306"
    command: --default-time-zone='America/Sao_Paulo' --max-binlog-size=10M

  mysql_recovery:
    image: mysql:8.0-debian
    container_name: mysql_binlog_recovery
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .mysql_recovery/data:/var/lib/mysql
    ports:
      - "5002:3306"
    command: --default-time-zone='America/Sao_Paulo' --max-binlog-size=10M
 